apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
  labels:
    name: zabbix
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: zabbix-mysql-data
  labels:
    type: local
  namespace: zabbix
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/data/kubedata/mysql"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zabbix-mysql-data-claim
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: zabbix-mysql-data
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: db-secret
  namespace: zabbix
data:
  db-root-pass: TG9ubGlmZTA5MDg=
  db-zbx-user: YWRtaW4=
  db-zbx-pass: cEBzc3cwcmQ=
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    app: zabbix
    tier: zabbix-web
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-web
        app: zabbix
    spec:
      hostNetwork: true
      hostAliases:
      - ip: "10.0.3.15"
        hostnames:
        - "zabbix-server"
      containers:
        - name: zabbix-web
          image: zabbix/zabbix-web-nginx-mysql:alpine-3.4-latest
          imagePullPolicy: Always
          resources:
           limits:
            cpu: 200m
            memory: 400Mi
           requests:
            cpu: 200m
            memory: 400Mi
          env:
            - name: DB_SERVER_HOST
              value: "10.0.3.15"
            - name: ZBX_SERVER_NAME
              value: "Zabbix kubernetes"
            - name: PHP_TZ
              value: "Asia/Shanghai"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-pass
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-root-pass
            - name: MYSQL_DATABASE
              value: "zabbix"
          volumeMounts:
            - name: zabbix-web-ssl
              mountPath: /etc/ssl/nginx
              readOnly: true
      volumes:
        - hostPath:
            path: /home/dotneft/zbx/zbx_env/etc/ssl/nginx/
          name: zabbix-web-ssl
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-server
  labels:
    app: zabbix
    tier: mysql-server
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-server
        app: zabbix
        tier: mysql-server
    spec:
      hostNetwork: true
      volumes:
       - name: zabbix-mysql-data
         persistentVolumeClaim:
          claimName: zabbix-mysql-data-claim
      containers:
        - name: zabbix-db
          image: percona:5.7
          env:
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-zbx-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-zbx-pass
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: db-root-pass
          - name: MYSQL_DATABASE
            value: "zabbix"
          volumeMounts:
            - mountPath: "/var/lib/mysql/"
              name: zabbix-mysql-data
              readOnly: false
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix
    tier: server
    environment: dev
  namespace: zabbix
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: zabbix-server
        app: zabbix
    spec:
      hostNetwork: true
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:alpine-3.4-latest
          imagePullPolicy: Always
          env:
            - name: DB_SERVER_HOST
              value: "10.0.3.15"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-zbx-pass
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-root-pass
            - name: MYSQL_DATABASE
              value: "zabbix"
            - name: ZBX_ENABLE_SNMP_TRAPS
              value: "true"
            - name: ZBX_STARTPROXYPOLLERS
              value: "5"
            - name: ZBX_PROXYCONFIGFREQUENCY
              value: "60"
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: true
        - name: zabbix-snmptraps
          image: zabbix/zabbix-snmptraps:ubuntu-3.4-latest
          imagePullPolicy: Always
          volumeMounts:
          - name: zabbix-db-storage
            mountPath: /var/lib/zabbix/snmptraps/
            readOnly: false
      volumes:
        - hostPath:
            path: /data/kubedata/zabbix/
          name: zabbix-db-storage
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: zabbix-agent
  labels:
    app: zabbix
    tier: agent
  namespace: zabbix
spec:
  updateStrategy:
   type: RollingUpdate
   rollingUpdate:
    maxUnavailable: 1
  template:
    metadata:
      labels:
        name: zabbix-agent
        app: zabbix
    spec:
      hostNetwork: true
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent:alpine-3.4-latest
          imagePullPolicy: Always
          resources:
           limits:
            cpu: 100m
            memory: 54Mi
           requests:
            cpu: 100m
            memory: 54Mi
          env:
            - name: ZBX_SERVER_HOST
              value: "10.195.24.12"
            - name: ZBX_PASSIVE_ALLOW
              value: "true"
            - name: ZBX_STARTAGENTS
              value: "3"
            - name: ZBX_TIMEOUT
              value: "10"
          securityContext:
            privileged: true
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: zabbix-web
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
